// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image2":
            case "matematica":return img`
. . . . . . . . . . . . . . . . 
. . . . f f f f f f f f f . . . 
. . . f 6 6 6 6 6 6 6 6 6 f . . 
. . . f 6 6 6 6 6 6 6 6 6 f . . 
. . . f 6 5 5 5 5 5 5 5 6 f . . 
. . . f 6 5 5 5 5 5 5 5 6 f . . 
. . . f 6 5 5 5 5 5 5 5 6 f . . 
. . . f 6 6 6 6 6 6 6 6 6 f . . 
. . . f 6 6 6 6 6 6 8 8 6 f . . 
. . . f 6 9 6 9 6 6 6 6 6 f . . 
. . . f 6 6 6 6 6 6 8 8 6 f . . 
. . . f 6 9 6 9 6 6 6 6 6 f . . 
. . . f 6 6 6 6 6 6 2 2 6 f . . 
. . . f 6 9 6 9 6 6 6 6 6 f . . 
. . . . f 6 6 6 6 6 6 6 6 f . . 
. . . . . f f f f f f f . . . . 
`;
            case "image5":
            case "premio":return img`
. . . . f f f f f f . . . . . . 
. . . f 5 5 5 5 5 5 f . . . . . 
. . f f 5 5 5 5 5 5 f f . . . . 
. f 5 5 5 5 5 5 5 5 5 5 f . . . 
. f 5 f 5 5 5 5 5 5 f 5 f . . . 
. f 5 f 5 5 5 5 5 5 f 5 f . . . 
. f 5 5 5 5 5 5 5 5 5 5 f . . . 
. . f f 5 5 5 5 5 5 f f . . . . 
. . . . f 5 5 5 5 f . . . . . . 
. . . . . f 5 5 f . . . . . . . 
. . . . f f 5 5 f f . . . . . . 
. . . f 5 5 5 5 5 5 f . . . . . 
. . f 5 5 5 5 5 5 5 5 f . . . . 
. f 5 5 5 5 5 5 5 5 5 5 f . . . 
. . f f f f f f f f f f . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image6":
            case "biblioteca":return img`
.cccccccccccccc.
cbddddddddddddbc
cddddddddddddddc
cddddddddddddddc
cddddddddddddddc
cddddddddddddddc
cddddddddddddddc
cbddddddddddddbc
ccbbbbbbbbbbbbcc
ccffffffffffffcc
cbc44c7c66c3ccbc
cbc44c7c66c3ccbc
fbc44c7c66c3ccbf
fdccccccccccccdf
fdcbbddddddbbcdf
fdffffffffffffdf
fdcc4c44c3c7ccdf
fdcc4c44c3c7ccdf
fdcccc44ccc7ccdf
fdccccccccccccdf
fdcbbddddddbbcdf
fdcbbddddddbbcdf
fdffffffffffffdf
ffffffffffffffff
`;
            case "image7":
            case "flor":return img`
. . . . . . . . 
. . . . . . . . 
. . . . . . . . 
. . c c c . . . 
. c c 6 6 c . . 
c c 3 3 f 6 c . 
c 6 c f 6 3 c . 
c 3 6 3 3 3 c . 
c 3 6 6 3 3 c . 
c 3 3 3 3 3 c . 
. c 3 3 3 6 . . 
. . 6 7 6 . . . 
. . 6 6 8 8 8 6 
. . 6 8 7 7 7 6 
. . 8 7 7 7 6 . 
. . 8 8 8 6 . . 
`;
            case "image8":
            case "biblioteca2":return img`
.cccccccccccccccccccccc.
cbddddddddddddddddddddbc
cddddddddddddddddddddddc
cddddddddddddddddddddddc
cddddddddddddddddddddddc
cddddddddddddddddddddddc
cddddddddddddddddddddddc
cbddddddddddddddddddddbc
ccbbbbbbbbbbbbbbbbbbbbcc
ccffffffffffffffffffffcc
cbcc55c9c66c3c7c66c3ccbc
cbcc55c9c66c3c7c66c3ccbc
fbcc55c9c66ccc7c66c3ccbf
fdccccccccccccccccccccdf
fdcbbddddddddddddddbbcdf
fdffffffffffffffffffffdf
fdccc6c33c4c6c55c3c7ccdf
fdccc6c33c4c6c55c3c7ccdf
fdccc6c33ccc6c55ccc7ccdf
fdccccccccccccccccccccdf
fdcbbddddddddddddddbbcdf
fdcbbddddddddddddddbbcdf
fdffffffffffffffffffffdf
ffffffffffffffffffffffff
`;
            case "image10":
            case "coração":return img`
....................
....................
....................
....................
....................
......bbb...bbb.....
.....b222b.b222b....
....b22222b22122b...
....b22222221122b...
....b22222212222b...
.....b222222222b....
......b2222222b.....
.......b22222b......
........b222b.......
.........b2b........
..........b.........
....................
....................
....................
....................
`;
            case "image9":
            case "maça":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . f 7 f 7 f . . . . . . 
. . . . . f f 7 f f . . . . . . 
. . . . f 2 2 2 2 2 f . . . . . 
. . . f 2 2 2 2 1 2 2 f . . . . 
. . . f 2 2 2 2 2 1 2 f . . . . 
. . . f 2 2 2 2 2 2 2 f . . . . 
. . . f 2 2 2 2 2 2 2 f . . . . 
. . . . f 2 2 2 2 2 f . . . . . 
. . . . . f f f f f . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image3":
            case "biologia":return img`
....................
....................
.........1..........
......661d1.........
.....177717766......
....1d177777677.....
..6.717777c77177....
...7c77767771d17....
...77677766771777...
..1777766677777767..
.1d1776717676777c7..
.7177661d176777777..
.77767771777777176..
.677c77777c7671d17..
.77777777777767176..
.667776776777777767.
...76776766676766...
....................
....................
....................
`;
            case "image11":
            case "chão":return img`
b d d d d d d c b d d d d d d c 
d b b b b b b c d b b b b b c c 
d b b b b b b c d b b b b c b c 
d b b b b b b c d b b b d d b c 
d b b b b b b c d b b c b b b c 
d b b b b b b c d b c c b b b c 
d b b b b b b b d b c c b b b b 
c c c c c c b a c c c c c c b a 
b d d d d d d c b d d d d d d c 
d b b b b b b c d b b b b b b c 
d b b b b b b c d b b b b b b c 
d b b b b b b c d b b b b b b c 
d b b b b b c c d b b b b b b c 
d b b b b c c c d b b b b b b c 
d b b b b c c b d b b b b b b b 
c c c c c c c a c c c c c c c a 
`;
            case "image13":
            case "armário":return img`
.cccccccccccccc.
cdbbbbbbbbbbbbdc
cbbbbbbbbbbbbbbc
cbbbbbbbbbbbbbbc
cbbbbbbbbbbbbbbc
cbbbbbbbbbbbbbbc
cbbbbbbbbbbbbbbc
cbbbbbbbbbbbbbbc
cbeeeeeeeeeeeebc
ceeeeeeeeeeeeeec
cebbbbbbbbbbbbec
ceceeeceeceeecec
feceeecddceeecef
feceeeecceeeecef
feccccccccccccef
feeeeeeeeeeeeeef
febbbbbbbbbbbbef
feceeeceeceeecef
feceeecddceeecef
feceeeecceeeecef
feccccccccccccef
feeeeeeeeeeeeeef
feffffffffffffef
ffffffffffffffff
`;
            case "image4":
            case "historia":return img`
.............................................
.............................................
.............................................
.............................................
.............................................
.............................................
.............................................
.............................................
........fffffffffffffffffffffffffffffff......
.......feeeeeeeeeeeeeeeefeeeeeeeeeeeeeeef....
.......feeeeeeeeeeeeeeeedeeeeeeeeeeeeeeef....
.......feeeefffffffffffedeeffffffffeeeeef....
.......feeef11111111111edf11111111661feef....
.......feeef111111111111d1111111116611fef....
.......feef1111111111111d1111111116611fef....
.......feef1111111111111d1111111116611fef....
.......feef1111111111111d1111111116611fef....
.......feef11bbbbbbbbb11d111bbbbbb66b1fef....
.......feef1111111111111d1111111116611fef....
.......feef1111111111111d1111111116611fef....
.......feef11bbbbbbbb111d111bbbbbb6611fef....
.......feef1111111111111d1111111116611fef....
.......feef1111111111111d1111111116611fef....
.......feef11bbbbbbbb111d111bbbbbb6611fef....
.......feef1111111111111d1111111116611fef....
.......feef1111111111111d1111111116611fef....
.......feef11bbbbbb11111d111bbbbb16611fef....
.......feef1111111111111d1111111116611fef....
.......feef1111111111111d1111111116611fef....
.......feef1111111111111d1111111116111fef....
.......feef1111111111111d1111111111111fef....
.......feef1111111111111d1111111111111fef....
.......feef1111111111111d1111111111111fef....
.......feef1111111111111d1111111111111fef....
.......feeff111111111111d111111111111feef....
.......feeef111111111111d111111111111feef....
.......feeeeeeeeeeeeeeeedffffffffffffeeef....
........feeeeeeeeeeeeeeefeeeeeeeeeeeeeeef....
...........fffffffffffffffffffffffffffff.....
.............................................
`;
            case "image14":
            case "livro":return img`
.............................................
.............................................
.............................................
.............................................
.............................................
.............................................
.............................................
.............................................
...........ffffffffffffff....................
.........ff1111111111111f....................
........fccaaaaaaaaaaaaaaf...................
........fccaaaaaaaaaaaaaaf...................
........fccaaaaaaaaaaaaaaf...................
........fccaaaaaaaaaaaaaaf...................
........fccaaaaaaaaaaaaaaf...................
........fccaaaaaaaaaaaaaaf...................
........fccaaafffffffaaaaf...................
........fbcaafbbbbbbbfaaaf...................
........fbcaafbbbbbbbfaaaf...................
........fbcaaafffffffaaaaf...................
........fbcaaaaaaaaaaaaaaf...................
........fbcaaaaaaaaaaaaaaf...................
........fbcaaaaaaaaaaaaaaf...................
........fbcaaaaaaaaaaaaaaf...................
........fbcaaaaaaaaaaaaaaf...................
........fbcaaaaaaaaaaaaaaf...................
........fbcaaaaaaaaaaaaaaf...................
........fccaaaaaaaaaaaaaaf...................
........fccaaaaaaaaaaaaaaf...................
........fccaaaaaaaaaaaaaaf...................
........fccaaaaaaaaaaaaaaf...................
........fccaaaaaaaaaaaaaaf...................
.........fffffffffffffffff...................
.............................................
.............................................
.............................................
.............................................
.............................................
.............................................
.............................................
`;
            case "image15":
            case "medalha":return img`
.................................................................
.................................................................
.................................................................
.................................................................
.................................................................
.................................................................
.................................................................
.................................................................
.................................................................
.................................................................
........................fffffffffffff8..ffffff...................
.......................f888888888888888888888888.................
........................f8888fffff8888fff88f8888.................
........................f888f...............f888.................
.........................f88.................88f.................
.........................f88f................88f.................
.........................f8ff...............f8f..................
.........................f88................88f..................
.........................f88...............f88f..................
..........................88f..............f88f..................
..........................f88..............88f...................
..........................f88..............88f...................
...........................f8f............f8f....................
............................88f..........f88.....................
............................f8f..........f8f.....................
............................f8f..........f8f.....................
.............................88..........88......................
.............................f8f........f8f......................
.............................f88f......f88f......................
..............................f88......88f.......................
..............................f88f....f88f.......................
...............................f88....88f........................
...............................f88f..f88f........................
................................f88ff88f.........................
................................f888888f.........................
..................................f88f...........................
...............................ffff88fff.........................
.............................ff555555555ff.......................
.............................f55555555555f.......................
............................f5555555555555f......................
...........................f555555555555555f.....................
..........................f55555555555555555f....................
..........................f55555555555555555f....................
..........................f55555555f55555555f....................
..........................f5555555f4f5555555f....................
..........................f555555f44f5555555f....................
..........................f5555555f4f5555555f....................
..........................f555555f444f555555f....................
..........................f5555555fff5555555f....................
..........................f55555555555555555f....................
...........................f555555555555555f.....................
............................f5555555555555f......................
.............................f55555555555f.......................
..............................f555555555f........................
...............................fffffffff.........................
.................................................................
.................................................................
.................................................................
.................................................................
.................................................................
`;
            case "image17":
            case "livro1":return img`
.............................................
.............................................
.............................................
..................ffffffffff.................
................fccccccccccaf................
................fccccccccccaf................
................fccccccccccaf................
................fccccccccccaf................
................fccccccccccaf................
................fccccccccccaf................
................fccccccccccaf................
................fccccbbbcccaf................
................fccccbbbcccaf................
................fccccbbbcccaf................
................fccccbbbcccaf................
................fccccbbbcccaf................
................fccccbbbcccaf................
................fccccbbbcccaf................
................fccccbbbcccaf................
................fccccbbbcccaf................
................fccccbbbcccaf................
................fccccbbbcccaf................
................fccccbbbcccaf................
................fccccbbbcccaf................
................fccccbbbcccaf................
................fccccbbbcccaf................
................fccccbbbcccaf................
................fccccbbbcccaf................
................fccccbbbcccaf................
................fccccccccccaf................
................fccccccccccaf................
................fccccccccccaf................
................fccccccccccaf................
................fccccccccccaf................
................fccccccccccaf................
.................ffffffffffff................
.............................................
.............................................
.............................................
.............................................
`;
            case "image18":
            case "livro2":return img`
.............................................
.............................................
.............................................
.............................................
..............ffffffffffffffffffff...........
............ff1111111111111111111f...........
...........fccaaaaaaaaaaaaaaaaaaaa...........
...........fccaaaaaaaaaaaaaaaaaaaaf..........
...........fccaaaaaaaaaaaaaaaaaaaaf..........
...........fccaaaaaaaaaaaaaaaaaaaaf..........
...........fccaaaaaaaaaaaaaaaaaaaaf..........
...........fccaaaaaaaaaaaaaaaaaaaaf..........
...........fccaaaaaaaaaaaaaaaaaaaaf..........
...........fccaaaafffffffffffffaaaf..........
...........fccaaaabbbbbbbbbbbbbfaaf..........
...........fbcaaafbbbbbbbbbbbbbfaaf..........
...........fbcaaafbbbbbbbbbbbbbfaaf..........
...........fbcaaafbbbbbbbbbbbbbfaaf..........
...........fbcaaafbbbbbbbbbbbbbfaaf..........
...........fbcaaaafffffffffffffaaaf..........
...........fbcaaaaaaaaaaaaaaaaaaaaf..........
...........fbcaaaaaaaaaaaaaaaaaaaaf..........
...........fbcaaaaaaaaaaaaaaaaaaaaf..........
...........fbcaaaaaaaaaaaaaaaaaaaaf..........
...........fbcaaaaaaaaaaaaaaaaaaaaf..........
...........fbcaaaaaaaaaaaaaaaaaaaaf..........
...........fbcaaaaaaaaaaaaaaaaaaaaf..........
...........fccaaaaaaaaaaaaaaaaaaaaf..........
...........fccaaaaaaaaaaaaaaaaaaaaf..........
...........fccaaaaaaaaaaaaaaaaaaaaf..........
...........fccaaaaaaaaaaaaaaaaaaaaf..........
...........fccaaaaaaaaaaaaaaaaaaaaf..........
...........fccaaaaaaaaaaaaaaaaaaaaf..........
...........fccaaaaaaaaaaaaaaaaaaaaf..........
...........fccaaaaaaaaaaaaaaaaaaaaf..........
...........fccaaaaaaaaaaaaaaaaaaaaf..........
...........fccffffffffffffffffffff...........
.............................................
.............................................
.............................................
`;
            case "image19":
            case "livro3":return img`
.............................................
.............................................
.............................................
.............................................
...............fffffffffffffff...............
...............aa11111111111aaf..............
..............faa11111111111aaf..............
..............faa11111111111aaf..............
..............faa111d1111111aaf..............
..............faa111d1111111aaf..............
..............faa111d1111111aaf..............
..............faa1d1d111d111aaf..............
..............faa1111111d111aaf..............
..............faa1111111d111aaf..............
..............faa111d1111111aaf..............
..............faa111d1111111aaf..............
..............faa111d111d111aaf..............
..............faa111d1111111aaf..............
..............faa111d1111111aaf..............
..............faa111d111d111aaf..............
..............faa111d111d111aaf..............
..............faa111d111d111aaf..............
..............faa111d111d111aaf..............
..............faa111d111d111aaf..............
..............faa1d1d111d111aaf..............
..............faa1d1d1111111aaf..............
..............faa1d1d111d111aaf..............
..............faa1d1d111d111aaf..............
..............faa1d1d111d111aaf..............
..............faa1d11111d111aaf..............
..............faa1d11111d111aaf..............
..............faa1d11111d111aaf..............
..............faa1d11111d111aaf..............
..............faa1d11111d111aaf..............
..............faa1d11111d111aaf..............
..............faa11111111111aaf..............
..............faa11111111111aaf..............
...............aa11111111111aaf..............
...............fffffffffffffff...............
.............................................
`;
            case "image20":
            case "myImage0":return img`
.............................................
.............................................
.............................................
...........ffffffffffffffffffffff............
..........ff11111111111111111111fff..........
..........faaaaaaaaaaaaaaaaaaaaaccf..........
..........faaaaaaaaaaaaaaaaaaaaaccf..........
..........faaaaaaaaaaaaaaaaaaaaaccf..........
..........faaaaaaaaaaaaaaaaaaaaaccf..........
..........faaaaaaaaaaaaaaaaaaaaaccf..........
..........faaaaaaaaaaaaaaaaaaaaaccf..........
..........faaaaaaaaaaaaaaaaaaaaaccf..........
..........faaaaaaaaaaaaaaaaaaaaaccf..........
..........faaaaaaaaaaaaaaaaaaaaaccf..........
..........faaaaaaaaaaaaaaaaaaaaacbf..........
..........faaaaaaaaaaaaaaaaaaaaacbf..........
..........faaaaaaaaaaaaaaaaaaaaacbf..........
..........faaaaaaaaaaaaaaaaaaaaacbf..........
..........faaaaaaaaaaaaaaaaaaaaacbf..........
..........faaaaaaaaaaaaaaaaaaaaacbf..........
..........faaaaaaaaaaaaaaaaaaaaacbf..........
..........faaaaaaaaaaaaaaaaaaaaacbf..........
..........faaaaaaaaaaaaaaaaaaaaacbf..........
..........faaaaaaaaaaaaaaaaaaaaacbf..........
..........faaaaaaaaaaaaaaaaaaaaacbf..........
..........faaaaaaaaaaaaaaaaaaaaacbf..........
..........faaaaaaaaaaaaaaaaaaaaacbf..........
..........faaaaaaaaaaaaaaaaaaaaaccf..........
..........faaaaaaaaaaaaaaaaaaaaaccf..........
..........faaaaaaaaaaaaaaaaaaaaaccf..........
..........faaaaaaaaaaaaaaaaaaaaaccf..........
..........faaaaaaaaaaaaaaaaaaaaaccf..........
..........faaaaaaaaaaaaaaaaaaaaaccf..........
..........faaaaaaaaaaaaaaaaaaaaaccf..........
..........faaaaaaaaaaaaaaaaaaaaaccf..........
..........faaaaaaaaaaaaaaaaaaaaaccf..........
..........faaaaaaaaaaaaaaaaaaaaaccf..........
...........fffffffffffffffffffffff...........
.............................................
.............................................
`;
            case "image12":
            case "personagem1":return img`
. . . . . f f f f . . . . . . . 
. . . f f f 1 1 f f f . . . . . 
. . f f f 1 1 1 1 f f f . . . . 
. f f f 8 8 8 8 8 8 f f f . . . 
. f f 8 1 1 1 1 1 1 8 8 f . . . 
. f 8 1 f f f f f f 1 8 f f . . 
. f f f f d d d d f f f f . . . 
f f 8 f b f d d f b f 8 f f . . 
f 8 8 d 1 f d d f 1 d 8 8 f . . 
. f 8 8 d d d d d d 8 8 f . . . 
. . f 8 8 d d d d 8 8 f . . . . 
. d d f 8 1 8 8 1 8 f d d . . . 
. d f f 8 1 8 8 1 8 f f d . . . 
. d d f 8 8 8 8 8 8 f d d . . . 
. . . . f f f f f f . . . . . . 
. . . . f f . . f f . . . . . . 
`;
            case "image21":
            case "personagem2":return img`
. . . . . f f f f . . . . . . . 
. . . f f f 1 1 f f f . . . . . 
. . f f f 1 1 1 1 f f f . . . . 
. f f f c c c c c c f f f . . . 
. f f c 1 1 1 1 1 1 c c f f . . 
. f c 1 f f f f f f 1 c f . . . 
. f f f f d d d d f f f f . . . 
f f c f b f d d f b f c f f . . 
f c c d 1 f d d f 1 d c c f . . 
. f c c d d d d d d c c f f . . 
. . f c c d d d d c c f . . . . 
. d d f c 1 c c 1 c f d d . . . 
. d f f c 1 c c 1 c f f d . . . 
. d d f c c c c c c f d d . . . 
. . . . f f f f f f . . . . . . 
. . . . f f . . f f . . . . . . 
`;
            case "image1":
            case "geografia":return img`
b b b b b b b b b b b b b b b b 
b b b b b b b b b b b b b b b b 
b b b b f f f f f f f b b b b b 
b b b f 7 8 8 8 8 8 8 f b b b b 
b b f 7 7 7 8 8 8 8 7 7 b b b b 
b b f 8 8 8 8 8 8 7 7 7 f b b b 
b b f 8 8 7 7 8 8 8 7 7 f b b b 
b b f 8 7 7 7 8 8 7 7 7 f b b b 
b b f 7 7 7 7 7 8 8 8 8 f b b b 
b b f 7 7 7 8 8 8 7 7 7 f b b b 
b b f 7 7 8 8 8 8 7 7 8 f b b b 
b b b f 8 8 8 8 8 8 7 f b b b b 
b b b b f f f f f f f b b b b b 
b b b b b b b b b b b b b b b b 
b b b b b b b b b b b b b b b b 
b b b b b b b b b b b b b b b b 
`;
            case "image23":
            case "myImage2":return img`
. . . . . . . . . . . . . . . . 
. . . . . f f f f f f . . . . . 
. . . . f 1 f 8 8 8 8 f f . . . 
. . . f 1 1 1 f 8 8 8 8 f f . . 
. . . f 8 8 8 8 f f 8 8 8 f . . 
. . f 8 f f f f 8 8 8 f f f . . 
. . f f 8 f f f f 8 8 8 8 f . . 
. . f f 8 8 8 8 f f f f f f f . 
. . f 8 8 d d f d 8 f f 8 f f . 
. . . f 8 d d f d 8 d f 8 8 f . 
. . . . f d d d 8 8 8 8 8 f . . 
. . . . f 8 8 8 d d 8 f . . . . 
. . . . f 8 8 8 d d 8 f . . . . 
. . . f f 8 8 f 8 8 f f f . . . 
. . . f f f f f f f f f f . . . 
. . . . f f f . . . f f . . . . 
`;
            case "image22":
            case "myImage1":return img`
. . . . . . . . . . . . . . . . 
. . . . . f f f f f f . . . . . 
. . . f f 8 8 8 8 f 1 f . . . . 
. . f f 8 8 8 8 f 1 1 1 f . . . 
. . f 8 8 8 f f 8 8 8 8 f . . . 
. . f f f f 8 8 f 8 f f 8 f . . 
. . f 8 8 8 8 f f f f 8 8 f . . 
. f f f f f f f 8 8 8 f f f . . 
. f f 8 f f 8 d f d d 8 8 f . . 
. f 8 8 f d f 1 f d d 8 f . . . 
. . f 8 8 8 8 8 d d d f . . . . 
. . . . f 8 d d 8 8 8 f . . . . 
. . . . f 8 d d 8 8 8 f . . . . 
. . . f f f 8 8 f 8 8 f f . . . 
. . . f f f f f f f f f f . . . 
. . . . f f . . . f f f . . . . 
`;
            case "image27":
            case "sabio":return img`
. . . . f f e e f . . . . . . . 
. . . f f e e e e f f f . . . . 
. . f e e e e e e e e f . . . . 
. . . f d f d f d f f . . . . . 
. . . f d d d d d f . . . . . . 
. . . f d 1 1 1 d f . . . . . . 
. . . . . 1 d 1 f . . . . . . . 
. . . . f 1 1 1 f . . . . . . . 
. . . f 4 1 1 1 4 f . . . . . . 
. . . f 4 1 1 1 4 f . . . . . . 
. . . f 4 1 1 1 4 f . . . . . . 
. . . f 4 4 4 4 4 f . . . . . . 
. . . f 4 4 4 4 4 f . . . . . . 
. . . . f 4 4 4 f . . . . . . . 
. . . . f c c c f . . . . . . . 
. . . . f c f c f . . . . . . . 
`;
            case "image16":
            case "myImage":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "livrocoleta":
            case "anim1":return [img`
.............................................
.............................................
.............................................
.............................................
.............................................
.................ffffffff....................
...............fcccccccca....................
...............fccccccccaf...................
...............fccccccccaf...................
...............fccccccccaf...................
...............fccccccccaf...................
...............fccccccccaf...................
...............fccccccccaf...................
...............fcccbbcccaf...................
...............fcccbbcccaf...................
...............fcccbbcccaf...................
...............fcccbbcccaf...................
...............fcccbbcccaf...................
...............fcccbbcccaf...................
...............fcccbbcccaf...................
...............fcccbbcccaf...................
...............fcccbbcccaf...................
...............fcccbbcccaf...................
...............fcccbbcccaf...................
...............fcccbbcccaf...................
...............fcccbbcccaf...................
...............fcccbbcccaf...................
...............fcccbbcccaf...................
...............fcccbbcccaf...................
...............fcccbbcccaf...................
...............fccccccccaf...................
...............fccccccccaf...................
...............fccccccccaf...................
...............fccccccccaf...................
...............fccccccccaf...................
...............fccccccccaf...................
...............fccccccccaf...................
................ffffffffff...................
.............................................
.............................................
`, img`
.............................................
.............................................
.............................................
.................fffffffffffffffffff.........
...............ff111111111111111111f.........
..............fccaaaaaaaaaaaaaaaaaaaf........
..............fccaaaaaaaaaaaaaaaaaaaf........
..............fccaaaaaaaaaaaaaaaaaaaf........
..............fccaaaaaaaaaaaaaaaaaaaf........
..............fccaaaaaaaaaaaaaaaaaaaf........
..............fccaaaaaaaaaaaaaaaaaaaf........
..............fccaaaaaaaaaaaaaaaaaaaf........
..............fccaaaaaaaaaaaaaaaaaaaf........
..............fccaaaffffffffffffaaaaf........
..............fccaafbbbbbbbbbbbbbaaaf........
..............fbcaafbbbbbbbbbbbbbfaaf........
..............fbcaafbbbbbbbbbbbbbfaaf........
..............fbcaafbbbbbbbbbbbbbfaaf........
..............fbcaafbbbbbbbbbbbbbfaaf........
..............fbcaaafffffffffffffaaaf........
..............fbcaaaaaaaaaaaaaaaaaaaf........
..............fbcaaaaaaaaaaaaaaaaaaaf........
..............fbcaaaaaaaaaaaaaaaaaaaf........
..............fbcaaaaaaaaaaaaaaaaaaaf........
..............fbcaaaaaaaaaaaaaaaaaaaf........
..............fbcaaaaaaaaaaaaaaaaaaaf........
..............fbcaaaaaaaaaaaaaaaaaaaf........
..............fccaaaaaaaaaaaaaaaaaaaf........
..............fccaaaaaaaaaaaaaaaaaaaf........
..............fccaaaaaaaaaaaaaaaaaaaf........
..............fccaaaaaaaaaaaaaaaaaaaf........
..............fccaaaaaaaaaaaaaaaaaaaf........
..............fccaaaaaaaaaaaaaaaaaaaf........
..............fccaaaaaaaaaaaaaaaaaaaf........
..............fccaaaaaaaaaaaaaaaaaaaf........
..............fccaaaaaaaaaaaaaaaaaaaf........
..............fccaaaaaaaaaaaaaaaaaaaf........
...............ccaaaaaaaaaaaaaaaaaaa.........
.................ffffffffffffffffff..........
.............................................
`, img`
.............................................
.............................................
.............................................
.............................................
.............................................
.................ffffffff....................
...............fc1111111af...................
...............fa1111111af...................
...............fa1111111af...................
...............fa11d1111af...................
...............fa11d1111af...................
...............fa11111d1af...................
...............fa11111d1af...................
...............fa11111d1af...................
...............fa1111111af...................
...............fa1d1d111af...................
...............fa111d111af...................
...............fa111d111af...................
...............fa111d111af...................
...............fa111d111af...................
...............fa111d111af...................
...............fa111d1d1af...................
...............fa111d111af...................
...............fa111d1d1af...................
...............fa111d1d1af...................
...............fa111d111af...................
...............fa1d1d111af...................
...............fa1d1d111af...................
...............fa1d111d1af...................
...............fa1d111d1af...................
...............fa1d111d1af...................
...............fa1d111d1af...................
...............fa1d111d1af...................
...............fa1d11111af...................
...............fa1d11111af...................
...............fa1111111af...................
...............fc1111111c....................
................fffffffff....................
.............................................
.............................................
`, img`
.............................................
.............................................
.............................................
.................fffffffffffffffffff.........
...............ff1111111111111111111f........
..............faaaaaaaaaaaaaaaaaaaccf........
..............faaaaaaaaaaaaaaaaaaaccf........
..............faaaaaaaaaaaaaaaaaaaccf........
..............faaaaaaaaaaaaaaaaaaaccf........
..............faaaaaaaaaaaaaaaaaaaccf........
..............faaaaaaaaaaaaaaaaaaaccf........
..............faaaaaaaaaaaaaaaaaaaccf........
..............faaaaaaaaaaaaaaaaaaaccf........
..............faaaaaaaaaaaaaaaaaaaccf........
..............faaaaaaaaaaaaaaaaaaaccf........
..............faaaaaaaaaaaaaaaaaaacbf........
..............faaaaaaaaaaaaaaaaaaacbf........
..............faaaaaaaaaaaaaaaaaaacbf........
..............faaaaaaaaaaaaaaaaaaacbf........
..............faaaaaaaaaaaaaaaaaaacbf........
..............faaaaaaaaaaaaaaaaaaacbf........
..............faaaaaaaaaaaaaaaaaaacbf........
..............faaaaaaaaaaaaaaaaaaacbf........
..............faaaaaaaaaaaaaaaaaaacbf........
..............faaaaaaaaaaaaaaaaaaacbf........
..............faaaaaaaaaaaaaaaaaaacbf........
..............faaaaaaaaaaaaaaaaaaacbf........
..............faaaaaaaaaaaaaaaaaaaccf........
..............faaaaaaaaaaaaaaaaaaaccf........
..............faaaaaaaaaaaaaaaaaaaccf........
..............faaaaaaaaaaaaaaaaaaaccf........
..............faaaaaaaaaaaaaaaaaaaccf........
..............faaaaaaaaaaaaaaaaaaaccf........
..............faaaaaaaaaaaaaaaaaaaccf........
..............faaaaaaaaaaaaaaaaaaaccf........
..............faaaaaaaaaaaaaaaaaaaccf........
..............faaaaaaaaaaaaaaaaaaaccf........
...............aaaaaaaaaaaaaaaaaaacc.........
.................ffffffffffffffffff..........
.............................................
`];
        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
